In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.Timestamp.now()

Timestamp('2023-03-23 13:59:56.756970')

In [6]:
url = 'https://github.com/prasertcbs/basic-dataset/raw/master/IMDB_Movie_1000_Data.csv'
df = pd.read_csv(url)
df.head(5)

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [7]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge,Lasso

In [10]:
df['genres'] = df['Genre'].str.split(',\s*') #\s = whitespace
df[:5]

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore                        genres  
0     8.1  757074              333.13       76.0   [Action, Adventure, Sci-Fi]  
1     7.0  485820              126.46       65.0  [Adventure, Mystery, Sci-Fi]  
2     7.3  157606              138.12       62.0            [Horror, Thriller]  
3     7.2   60545              270.32       59.0   [Animation, Comedy, Family]  
4     6.2  393727              325.02       40.0  [Action, Adventure, Fantasy]

In [11]:
mlb = MultiLabelBinarizer()
mlb.fit(df['genres'])

MultiLabelBinarizer()

In [12]:
mlb.classes_

array(['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller',
       'War', 'Western'], dtype=object)

In [16]:
df['genres'].explode().unique()

array(['Action', 'Adventure', 'Sci-Fi', 'Mystery', 'Horror', 'Thriller',
       'Animation', 'Comedy', 'Family', 'Fantasy', 'Drama', 'Music',
       'Biography', 'Romance', 'History', 'Crime', 'Western', 'War',
       'Musical', 'Sport'], dtype=object)

In [17]:
mlb.transform(df['genres'])

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
dg = pd.DataFrame(mlb.fit_transform(df['genres']),columns=mlb.classes_)
dg[:3]

Action  Adventure  Animation  Biography  Comedy  Crime  Drama  Family  \
0       1          1          0          0       0      0      0       0   
1       0          1          0          0       0      0      0       0   
2       0          0          0          0       0      0      0       0   

   Fantasy  History  Horror  Music  Musical  Mystery  Romance  Sci-Fi  Sport  \
0        0        0       0      0        0        0        0       1      0   
1        0        0       0      0        0        1        0       1      0   
2        0        0       1      0        0        0        0       0      0   

   Thriller  War  Western  
0         0    0        0  
1         0    0        0  
2         1    0        0

In [22]:
mlb.classes_

array(['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime',
       'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller',
       'War', 'Western'], dtype=object)

In [23]:
mlb.inverse_transform(dg.to_numpy())[:3]

[('Action', 'Adventure', 'Sci-Fi'),
 ('Adventure', 'Mystery', 'Sci-Fi'),
 ('Horror', 'Thriller')]

In [24]:
df['g2'] = pd.Series(mlb.inverse_transform(dg.to_numpy()))
df[:3]

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   

                                         Description            Director  \
0  A group of intergalactic criminals are forced ...          James Gunn   
1  Following clues to the origin of mankind, a te...        Ridley Scott   
2  Three girls are kidnapped by a man with a diag...  M. Night Shyamalan   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   

   Rating   Votes  Revenue (Millions)  Metascore  \
0     8.1  757074              333.13       76.0   
1     7.0  485820              126.46       65.0   
2     7.3  157606              138.12       62.0   

                         genres                            g2  
0   [Action, Adventure, Sci-Fi]   (Action, Adventure, Sci-Fi)  
1  [Adventure, Mystery, Sci-Fi]  (Adventure, Mystery, Sci-Fi)  
2            [Horror, Thriller]            (Horror, Thriller)

In [25]:
df['g2'].str.join(',')

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...           
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: g2, Length: 1000, dtype: object

In [27]:
dg.loc[0]

Action       1
Adventure    1
Animation    0
Biography    0
Comedy       0
Crime        0
Drama        0
Family       0
Fantasy      0
History      0
Horror       0
Music        0
Musical      0
Mystery      0
Romance      0
Sci-Fi       1
Sport        0
Thriller     0
War          0
Western      0
Name: 0, dtype: int32

In [33]:
g = np.array([dg.loc[0],dg.loc[1],dg.loc[4]])
mlb.inverse_transform(g)

[('Action', 'Adventure', 'Sci-Fi'),
 ('Adventure', 'Mystery', 'Sci-Fi'),
 ('Action', 'Adventure', 'Fantasy')]

In [35]:
np.array(dg.loc[0])

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [39]:
g = np.array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1]])
mlb.inverse_transform(g)

[('Action', 'Adventure', 'Sci-Fi'),
 ('Action', 'Adventure', 'Music', 'War', 'Western')]

In [40]:
df = pd.concat([df,dg],axis=1)
df

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  ...  Horror  Music Musical Mystery  \
0                  121     8.1  757074  ...       0      0       0       0   
1                  124     7.0  485820  ...       0      0       0       1   
2                  117     7.3  157606  ...       1      0       0       0   
3                  108     7.2   60545  ...       0      0       0       0   
4                  123     6.2  393727  ...       0      0       0       0   
..                 ...     ...     ...  ...     ...    ...     ...     ...   
995                111     6.2   27585  ...       0      0       0       1   
996                 94     5.5   73152  ...       1      0       0       0   
997                 98     6.2   70699  ...       0      1       0       0   
998                 93     5.6    4881  ...       0      0       0       0   
999                 87     5.3   12435  ...       0      0       0       0   

     Romance  Sci-Fi  Sport  Thriller  War  Western  
0          0       1      0         0    0        0  
1          0       1      0         0    0        0  
2          0       0      0         1    0        0  
3          0       0      0         0    0        0  
4          0       0      0         0    0        0  
..       ...     ...    ...       ...  ...      ...  
995        0       0      0         0    0        0  
996        0       0      0         0    0        0  
997        1       0      0         0    0        0  
998        0       0      0  

In [41]:
df.dropna(inplace=True)

## sklearn : LinearRegression

In [43]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'genres', 'g2', 'Action', 'Adventure', 'Animation',
       'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'History',
       'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport',
       'Thriller', 'War', 'Western'],
      dtype='object')

In [46]:
X = df[['Runtime (Minutes)','Rating','Votes','Metascore','Action','Adventure', 'Animation',
       'Biography', 'Comedy', 'Crime', 'Drama', 'Family','Fantasy', 'History',
       'Horror','Music','Mystery','Romance','Sci-Fi','Thriller','War','Western']]

y = df['Revenue (Millions)']

In [47]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 838 entries, 0 to 999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Runtime (Minutes)  838 non-null    int64  
 1   Rating             838 non-null    float64
 2   Votes              838 non-null    int64  
 3   Metascore          838 non-null    float64
 4   Action             838 non-null    int32  
 5   Adventure          838 non-null    int32  
 6   Animation          838 non-null    int32  
 7   Biography          838 non-null    int32  
 8   Comedy             838 non-null    int32  
 9   Crime              838 non-null    int32  
 10  Drama              838 non-null    int32  
 11  Family             838 non-null    int32  
 12  Fantasy            838 non-null    int32  
 13  History            838 non-null    int32  
 14  Horror             838 non-null    int32  
 15  Music              838 non-null    int32  
 16  Mystery            838 non

In [48]:
test_size = .3
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=test_size,random_state=7)

In [50]:
model = LinearRegression()
model

LinearRegression()

In [51]:
model.fit(X_train,y_train)

LinearRegression()

In [52]:
model.score(X_train,y_train)

0.5726696280311907

In [53]:
model.intercept_

4.559321311985727

In [54]:
model.coef_

array([ 9.40352619e-01, -1.56790780e+01,  3.08627171e-04,  3.56937783e-01,
        1.24755022e+01,  2.78981360e+01,  1.00064843e+02,  3.19616480e+00,
       -9.36274458e-01, -1.74168581e+01, -2.79471716e+01,  2.25421662e+01,
        1.43519754e+01, -4.65335480e+00, -9.02213840e+00,  5.10484833e+00,
       -1.30694753e+01, -4.64000289e+00, -2.48969927e+00, -4.28189034e+00,
       -2.64791079e+01,  6.71424877e+00])

In [55]:
len(X.columns)

22

In [56]:
X[:3]

Runtime (Minutes)  Rating   Votes  Metascore  Action  Adventure  Animation  \
0                121     8.1  757074       76.0       1          1          0   
1                124     7.0  485820       65.0       0          1          0   
2                117     7.3  157606       62.0       0          0          0   

   Biography  Comedy  Crime  ...  Fantasy  History  Horror  Music  Mystery  \
0          0       0      0  ...        0        0       0      0        0   
1          0       0      0  ...        0        0       0      0        1   
2          0       0      0  ...        0        0       1      0        0   

   Romance  Sci-Fi  Thriller  War  Western  
0        0       1         0    0        0  
1        0       1         0    0        0  
2        0       0         1    0        0  

[3 rows x 22 columns]

In [57]:
model.predict(X_test)

array([130.07340751,  38.70794649,  14.13421054,  92.69671655,
        30.26725377, 211.02759789,  54.97498221, 438.88121453,
       115.18713205,  75.12026431, 112.82057122,  -6.34044986,
        51.22588274, 202.33097164,  -2.9038598 , 312.20626856,
        17.947256  ,  93.85155886,  96.6334835 ,  -3.48951708,
        91.75324715, 193.48296832, 124.70225265,  34.36987608,
       177.30532496,  -1.80931436, 198.5017026 , 164.5468235 ,
       137.63248895,  92.71041263,  46.67890898, 225.60162612,
        83.76642271,  34.81472185,  58.08162401,  36.02351874,
       219.63875506,  61.14307179,  44.28210247, -37.27356734,
       139.37786055,  37.70000176,  23.05587051,  17.09155609,
       119.3038578 , 166.95160088,  37.46068849,  82.18422775,
       155.46107787,  38.96730342,  14.01678003,  -3.47688646,
       124.5047579 ,  36.07602482,  90.31614142, 173.40849289,
       132.08959397,  12.2632741 , 158.52482742, 198.20346654,
        60.70002118, 153.39904834, 356.39140891, 198.87

In [58]:
dt = y_test.reset_index()
dt[:3]

index  Revenue (Millions)
0    267               27.10
1    831               49.00
2     72                3.73

In [61]:
dt['y_pred'] = model.predict(X_test)
dt['dif'] = dt['Revenue (Millions)']-dt['y_pred']
dt

index  Revenue (Millions)      y_pred         dif
0      267               27.10  130.073408 -102.973408
1      831               49.00   38.707946   10.292054
2       72                3.73   14.134211  -10.404211
3      423              106.37   92.696717   13.673283
4      986               42.58   30.267254   12.312746
..     ...                 ...         ...         ...
247    857               36.58    0.480247   36.099753
248    388              132.55  186.968504  -54.418504
249      2              138.12   57.590916   80.529084
250    257              176.74  120.775922   55.964078
251    368              262.03  233.013303   29.016697

[252 rows x 4 columns]

In [69]:
model = [[LinearRegression(),'LinearRegreesion'],[Ridge(alpha=1),'Ridge'],[Lasso(alpha=1),'Lasso']]
mp = []
for m in model:
    mx=m[0]
    mx.fit(X_train,y_train)
    mp.append([m[1],mx.score(X_test,y_test)])
mp

[['LinearRegreesion', 0.5756848203731457],
 ['Ridge', 0.5758421210242659],
 ['Lasso', 0.5636495020827571]]