## OneHotEncoder (dummy variable)

In [2]:
import pandas as pd
import numpy as np

import requests
%config inlineBackend.figure_format = 'retina'

In [2]:
pd.Timestamp.now()

Timestamp('2023-04-09 18:54:44.914601')

In [4]:
r = requests.get('https://github.com/prasertcbs/basic-dataset/raw/master/bank/bank-names.txt')
print(r.text)

Citation Request:
  This dataset is public available for research. The details are described in [Moro et al., 2011]. 
  Please include this citation if you plan to use this database:

  [Moro et al., 2011] S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (Eds.), Proceedings of the European Simulation and Modelling Conference - ESM'2011, pp. 117-121, Guimarães, Portugal, October, 2011. EUROSIS.

  Available at: [pdf] http://hdl.handle.net/1822/14838
                [bib] http://www3.dsi.uminho.pt/pcortez/bib/2011-esm-1.txt

1. Title: Bank Marketing

2. Sources
   Created by: Paulo Cortez (Univ. Minho) and Sérgio Moro (ISCTE-IUL) @ 2012
   
3. Past Usage:

  The full dataset was described and analyzed in:

  S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (Eds.), Proceedings of the European S

In [3]:
url = 'https://github.com/prasertcbs/basic-dataset/raw/master/bank/bank.csv'

In [4]:
df = pd.read_csv(url,sep=';')
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
df['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [7]:
ohenc1 = OneHotEncoder(sparse=False)
m1 = ohenc1.fit_transform(df[['marital']])
m1

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
ohenc1.categories_

[array(['divorced', 'married', 'single'], dtype=object)]

In [9]:
df[:3]

age         job  marital  education default  balance housing loan  \
0   30  unemployed  married    primary      no     1787      no   no   
1   33    services  married  secondary      no     4789     yes  yes   
2   35  management   single   tertiary      no     1350     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no

In [10]:
ohenc1.inverse_transform([[0,1,0],[1,0,0],[0,0,1]])

array([['married'],
       ['divorced'],
       ['single']], dtype=object)

In [11]:
ohenc2 = OneHotEncoder(sparse=False,drop='first')
m2 = ohenc2.fit_transform(df[['marital']])
m2

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [12]:
ohenc2.inverse_transform([[0,0],[1,0],[0,1]])

array([['divorced'],
       ['married'],
       ['single']], dtype=object)

In [17]:
ohenc = OneHotEncoder(sparse=False)
m3 = ohenc.fit_transform(df[['marital','default','education']])
m3

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [20]:
ohenc.feature_names_in_

array(['marital', 'default', 'education'], dtype=object)

In [19]:
pd.DataFrame(m3,columns=ohenc.categories_)

ValueError: all arrays must be same length

In [39]:
ohenc.categories_

[array(['divorced', 'married', 'single'], dtype=object),
 array(['no', 'yes'], dtype=object),
 array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)]

In [49]:
ohenc.inverse_transform([[0,0,0,0,0,0]])

array([['divorced', 'no', 'primary']], dtype=object)

In [66]:
df = pd.concat([df,pd.get_dummies(df[['marital','default']],prefix=['marital','default'])],axis=1).drop(['marital','default'],axis=1)

In [67]:
df

age            job  education  balance housing loan   contact  day  \
0      30     unemployed    primary     1787      no   no  cellular   19   
1      33       services  secondary     4789     yes  yes  cellular   11   
2      35     management   tertiary     1350     yes   no  cellular   16   
3      30     management   tertiary     1476     yes  yes   unknown    3   
4      59    blue-collar  secondary        0     yes   no   unknown    5   
...   ...            ...        ...      ...     ...  ...       ...  ...   
4516   33       services  secondary     -333     yes   no  cellular   30   
4517   57  self-employed   tertiary    -3313     yes  yes   unknown    9   
4518   57     technician  secondary      295      no   no  cellular   19   
4519   28    blue-collar  secondary     1137      no   no  cellular    6   
4520   44   entrepreneur   tertiary     1136     yes  yes  cellular    3   

     month  duration  campaign  pdays  previous poutcome   y  \
0      oct        79         1     -1         0  unknown  no   
1      may       220         1    339         4  failure  no   
2      apr       185         1    330         1  failure  no   
3      jun       199         4     -1         0  unknown  no   
4      may       226         1     -1         0  unknown  no   
...    ...       ...       ...    ...       ...      ...  ..   
4516   jul       329         5     -1         0  unknown  no   
4517   may       153         1     -1         0  unknown  no   
4518   aug       151        11     -1         0  unknown  no   
4519   feb       129         4    211         3    other  no   
4520   apr       345         2    249         7    other  no   

      marital_divorced  marital_married  marital_single  default_no  \
0                    0                1               0           1   
1                    0                1               0           1   
2                    0                0               1           1   
3                    0                1               0           1   
4                    0                1               0           1   
...                ...              ...             ...         ...   
4516                 0                1               0           1   
4517                 0                1               0           0   
4518                 0                1               0           1   
4519                 0                1               0           1   
4520                 0                0               1           1   

      default_yes  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
4516            0  
4517            1  
4518            0  
4519            0  
4520            0  

[4521 rows x 20 columns]